// Throw, try and catch
//console.log(c+d);

try {
    console.log(a+b);

} catch (err) {
    console.log(err)
    console.log("They was an error");

}
console.log("my program does not stop")

// The code will continue to run even if they is an error


